name: Run hexcode pull

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 6"
  
jobs:
  file-validation:
    runs-on: ubuntu-latest
    steps:
      # checkout repo
      - uses: actions/checkout@v4
      
      - name: run file validation
        run: bash output_validation.sh
        working-directory: ./output_validation

      # Commit the diff'd csv files
      - uses: EndBug/add-and-commit@v9
        with: 
          add: 'output_validation/full_diff*.csv output_validation/only_discrepancies*.csv'