name: Run hexcode pull and prod LCF

on:
  push:
    paths:
      - 'pull_hexcodes/final_augmented_runninglist.csv'
  
jobs:
  weekly-task:
    runs-on: ubuntu-latest
    steps:
      # checkout repo
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.9.9" # pin a specific version is best practice
          enable-cache: true

      - name: run clinical LCF workflow
        run: uv run main.py -o lineage_class.csv
      
      - name: run wastewater LCF workflow
        run: uv run main.py --workflow-type wastewater -o lineage_class_wastewater.csv
      
      # Commit just the lineage classification files
      - uses: EndBug/add-and-commit@v9
        with: 
          add: 'lineage_class.csv lineage_class_wastewater.csv'
